# Generated by Django 2.0 on 2018-07-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apikey', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=100)),
                ('secure_hash', models.CharField(max_length=1024)),
                ('password', models.CharField(max_length=100)),
                ('send_url', models.URLField()),
                ('test', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
    ]
