# Generated by Django 2.0.5 on 2018-05-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bit_location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('slave_id', models.IntegerField()),
                ('eventid', models.IntegerField()),
                ('event_name', models.CharField(max_length=100)),
                ('event_msg', models.TextField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('port', models.IntegerField()),
                ('query_frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_slaves', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slaves.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='slave',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slaves.System'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='slave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slaves.Slave'),
        ),
        migrations.AddField(
            model_name='flag',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slaves.Sensor'),
        ),
    ]
