# Generated by Django 2.0.5 on 2018-05-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subordinates', '0002_subordinate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='isFlags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='nbytes',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
