# Generated by Django 2.0.5 on 2018-05-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subordinates', '0003_auto_20180525_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='nbytes',
            new_name='nregisters',
        ),
    ]
