# Generated by Django 2.0 on 2018-06-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0004_auto_20180525_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='address',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
