# Generated by Django 2.0.5 on 2018-06-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subordinates', '0005_threshold_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='threshold',
            field=models.IntegerField(),
        ),
    ]
