# Generated by Django 2.0 on 2018-06-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subordinates', '0008_auto_20180618_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='threshold',
            field=models.FloatField(),
        ),
    ]
