# Generated by Django 2.0 on 2018-06-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subordinates', '0009_auto_20180630_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='subordinate',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
