# Generated by Django 2.0 on 2018-07-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0010_slave_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('alert_type', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email')], default='Email', max_length=5)),
                ('enabled', models.BooleanField(default=False)),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=1000)),
            ],
        ),
    ]
