# Generated by Django 2.0 on 2018-07-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subordinates', '0011_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='default_expiry_time',
            field=models.IntegerField(default=0, verbose_name='In minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
