# Generated by Django 2.0.8 on 2018-12-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0015_auto_20181201_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='has_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='icon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='icon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
